### ISSUE TITLE
Custom graphics

### ISSUE THREAD

**Issue by Angelk90** [MrToph/react-native-simple-notification#1]
Hi @MrToph , would it be possible to create a graphic like this with push notification? 
![](https://i.imgur.com/CsU8Myb.jpg)

**Comment by MrToph** [comment]
I don't think Android / Iphone supports such a custom setup.

**Comment by Angelk90** [comment]
@MrToph : 
Look here: 
https://github.com/zo0r/react-native-push-notification/issues/762#issuecomment-403202654

**Comment by Angelk90** [comment]
@MrToph :
Look here:
zo0r/react-native-push-notification#762 (comment)
